# -*- mode: python ; coding: utf-8 -*-
"""MeshCtx Desktop — PyInstaller spec v2.41 FULL"""
import sys, os
from PyInstaller.utils.hooks import collect_submodules
_here = r'E:\Meshctx'
block_cipher = None

a = Analysis(
    ['meshctx_desktop.py'],
    pathex=[_here, os.path.join(_here, 'src')],
    binaries=[],
    datas=[
        ('logo.png', '.'), ('logo.ico', '.'), ('logo.icns', '.'),
        ('version_info.txt', '.'), ('meshctx.yaml', '.'),
        ('src/__init__.py', 'src'),
        ('src/core/__init__.py', 'src/core'),
        ('src/core/*.py', 'src/core'),
        ('src/*.py', 'src'),
        ('plugins/registry.json', 'plugins'),
    ],
    hiddenimports=collect_submodules('src.core') + collect_submodules('src') + [
        # Desktop deps
        'webview', 'webview.platforms', 'webview.js',
        'webview.guilib', 'webview.util',
        # 完整核心模块列表 (102 模块 — 自动生成,勿手动编辑)
        'src.core.acp_server',
        'src.core.action_gate',
        'src.core.active_inference',
        'src.core.alert_engine',
        'src.core.agent_swarm',
        'src.core.agent_benchmark',
        'src.core.benchmark_engine',
        'src.core.agent_loop',
        'src.core.agent_monitor',
        'src.core.agent_tasks',
        'src.core.agent_teams',
        'src.core.approval',
        'src.core.attention_decay',
        'src.core.autonomous_action',
        'src.core.attractor_reasoner',
        'src.core.augmented_memory',
        'src.core.auto_healer',
        'src.core.auto_tuner',
        'src.core.auto_update',
        'src.core.autonomous_bugfix',
        'src.core.autonomous_engine',
        'src.core.backup_vault',
        'src.core.behavior_monitor',
        'src.core.brain_router',
        'src.core.brain_validator',
        'src.core.breakthrough_memory',
        'src.core.cache',
        'src.core.checkpoint',
        'src.core.code_reviewer',
        'src.core.cognitive_health',
        'src.core.context_compressor',
        'src.core.context_restorer',
        'src.core.conversation_store',
        'src.core.credential_pool',
        'src.core.cross_validator',
        'src.core.crypto',
        'src.core.desktop_agent',
        'src.core.deploy_engine',
        'src.core.distributed_mesh',
        'src.core.dashboard',
        'src.core.diff_preview',
        'src.core.evolution_tracker',
        'src.core.feedback_loop',
        'src.core.error_learner',
        'src.core.feishu_notify',
        'src.core.free_energy',
        'src.core.gateway_connectors',
        'src.core.gateway_llm',
        'src.core.global_workspace',
        'src.core.goal_decomposer',
        'src.core.healer',
        'src.core.health_monitor',
        'src.core.homeostasis',
        'src.core.hooks_engine',
        'src.core.hotreload',
        'src.core.human_memory',
        'src.core.hybrid_reasoning',
        'src.core.image_gen',
        'src.core.info_geo_router',
        'src.core.autopilot',
        'src.core.auto_deploy',
        'src.core.category_composer',
        'src.core.causal_analyzer',
        'src.core.pipeline_bench',
        'src.core.plugin_adapter',
        'src.core.swarm_engine',
        'src.core.thermo_cost',
        'src.core.topo_memory',
        'src.core.wasserstein_bridge',
        'src.core.knowledge_graph',
        'src.core.kernel',
        'src.core.knowledge_sync',
        'src.core.intent_predict_v2',
        'src.core.knowledge_transfer',
        'src.core.learn_loop',
        'src.core.llm_quality',
        'src.core.memory_health',
        'src.core.memory_hierarchy',
        'src.core.memory_v2',
        'src.core.metacognition',
        'src.core.model_compare',
        'src.core.multi_agent',
        'src.core.multi_notify',
        'src.core.online_learning',
        'src.core.orchestrator',
        'src.core.performance',
        'src.core.permission_intel',
        'src.core.performance_optimizer',
        'src.core.platform_fs',
        'src.core.plugin_autoload',
        'src.core.plugin_manifest',
        'src.core.plugin_hotreload',
        'src.core.plugin_market',
        'src.core.pre_action_check',
        'src.core.predictive_precompute',
        'src.core.predictor',
        'src.core.principle_extractor',
        'src.core.profile_manager',
        'src.core.progressive_context',
        'src.core.project_indexer',
        'src.core.prompt_shield',
        'src.core.realtime_push',
        'src.core.regression_shield',
        'src.core.sandbox',
        'src.core.self_debug',
        'src.core.sdb_framework',
        'src.core.secret_scanner',
        'src.core.security',
        'src.core.security_audit',
        'src.core.self_modify',
        'src.core.self_updater',
        'src.core.session_archiver',
        'src.core.session_identity',
        'src.core.session_resume',
        'src.core.smart_router',
        'src.core.subconscious',
        'src.core.super_brain',
        'src.core.task_progress',
        'src.core.telegram_router',
        'src.core.unified_loop',
        'src.core.usage_insights',
        'src.core.version_guard',
        'src.core.versioned_memory',
        'src.core.voice_io',
        'src.core.watchdog',
        'src.core.webhook',
        'src.core.websocket_plugin',
        'src.core.win_admin',
        'src.core.workflow_engine',
        'src.core.workspace_manager',
        'src.core.agent_factory',
        'src.core.agents_md',
        'src.core.claude_bench',
        'src.core.config_migrate',
        'src.core.consensus',
        'src.core.interactive_console',
        'src.core.jepa_router',
        'src.core.jepa_world_model',
        'src.core.knowledge_synth',
        'src.core.log_agg',
        'src.core.mcp_integrator',
        'src.core.notify',
        'src.core.persona',
        'src.core.rate_limiter',
        'src.core.roi_analytics',
        'src.core.scheduler',
        'src.core.self_opt_router',
        'src.core.self_healing2',
        'src.core.usage_tracker',
        'src.core.v300_report',
        # v3.00+ 新模块 (30个)
        'src.core.aliases',
        'src.core.api_docs',
        'src.core.content_type',
        'src.core.data_export',
        'src.core.datetime_utils',
        'src.core.dep_graph',
        'src.core.dep_resolver',
        'src.core.diff_engine',
        'src.core.env_diag',
        'src.core.error_codes',
        'src.core.event_bus',
        'src.core.feature_flags',
        'src.core.hash_utils',
        'src.core.hot_reload',
        'src.core.import_opt',
        'src.core.jwt_mgr',
        'src.core.kv_store',
        'src.core.metrics_collect',
        'src.core.path_match',
        'src.core.profiler',
        'src.core.random_gen',
        'src.core.regex_tools',
        'src.core.scaffolder',
        'src.core.schema_validator',
        'src.core.session_replay',
        'src.core.str_format',
        'src.core.template_engine',
        'src.core.ts_predict',
        'src.core.url_builder',
        'src.core.work_queue',
        'src.core.agent_governance',
        # Common deps
# Common deps
        'yaml', 'openai', 'httpx', 'fastapi', 'uvicorn',
        'pydantic', 'jinja2', 'Crypto', 'Crypto.Cipher',
        'Crypto.Cipher.AES', 'aiohttp', 'starlette',
        'anyio', 'sniffio', 'h11', 'websockets', 'psutil',
        'numpy', 'aiofiles', 'packaging',
    ],
    hookspath=[],
    excludes=['torch','tensorflow','sklearn','keras','onnxruntime','torchvision','torchaudio','xgboost','lightgbm','numba','cupy'],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],
    name='meshctx-desktop', debug=False, strip=False, upx=True,
    console=True, icon='logo.ico',
    version='version_info.txt')

if sys.platform == 'darwin':
    app = BUNDLE(exe, name='meshctx-desktop.app', icon='logo.icns',
        bundle_identifier='com.meshctx.desktop',
        info_plist={
            'NSHighResolutionCapable': 'True',
            'CFBundleShortVersionString': '3.47.0',
            'CFBundleVersion': '3.47.0',
        }, version='version_info.txt')
