# -*- mode: python ; coding: utf-8 -*-
"""MeshCtx Desktop — PyInstaller spec v2.41 FULL"""
import sys, os
from PyInstaller.utils.hooks import collect_submodules
_here = os.path.dirname(os.path.abspath(SPECPATH)) if 'SPECPATH' in globals() else os.path.dirname(os.path.abspath(__file__))
block_cipher = None

a = Analysis(
    ['meshctx_desktop.py'],
    pathex=[_here, os.path.join(_here, 'src')],
    binaries=[],
    datas=[
        ('logo.png', '.'), ('logo.ico', '.'), ('logo.icns', '.'),
        ('version_info.txt', '.'), ('meshctx.yaml', '.'),
        ('src/__init__.py', 'src'),
        ('src/core/__init__.py', 'src/core'),
        ('src/core/*.py', 'src/core'),
        ('src/*.py', 'src'),
        ('plugins/registry.json', 'plugins'),
    ],
    hiddenimports=collect_submodules('src.core') + collect_submodules('src') + [
        # Desktop deps
        'webview', 'webview.platforms', 'webview.js',
        'webview.guilib', 'webview.util',
        # 完整核心模块列表 (102 模块 — 自动生成,勿手动编辑)
        'src.core.acp_server',
        'src.core.action_gate',
        'src.core.active_inference',
        'src.core.agent_benchmark',
        'src.core.agent_loop',
        'src.core.agent_monitor',
        'src.core.agent_tasks',
        'src.core.agent_teams',
        'src.core.approval',
        'src.core.attention_decay',
        'src.core.attractor_reasoner',
        'src.core.augmented_memory',
        'src.core.auto_healer',
        'src.core.auto_tuner',
        'src.core.auto_update',
        'src.core.autonomous_bugfix',
        'src.core.autonomous_engine',
        'src.core.backup_vault',
        'src.core.behavior_monitor',
        'src.core.brain_router',
        'src.core.brain_validator',
        'src.core.breakthrough_memory',
        'src.core.cache',
        'src.core.checkpoint',
        'src.core.code_reviewer',
        'src.core.cognitive_health',
        'src.core.context_compressor',
        'src.core.context_restorer',
        'src.core.conversation_store',
        'src.core.credential_pool',
        'src.core.cross_validator',
        'src.core.crypto',
        'src.core.dashboard',
        'src.core.diff_preview',
        'src.core.error_learner',
        'src.core.feishu_notify',
        'src.core.free_energy',
        'src.core.gateway_connectors',
        'src.core.gateway_llm',
        'src.core.global_workspace',
        'src.core.goal_decomposer',
        'src.core.healer',
        'src.core.health_monitor',
        'src.core.homeostasis',
        'src.core.hooks_engine',
        'src.core.hotreload',
        'src.core.human_memory',
        'src.core.hybrid_reasoning',
        'src.core.image_gen',
        'src.core.info_geo_router',
        'src.core.kernel',
        'src.core.knowledge_transfer',
        'src.core.learn_loop',
        'src.core.llm_quality',
        'src.core.memory_health',
        'src.core.memory_hierarchy',
        'src.core.memory_v2',
        'src.core.metacognition',
        'src.core.model_compare',
        'src.core.multi_agent',
        'src.core.multi_notify',
        'src.core.online_learning',
        'src.core.orchestrator',
        'src.core.performance',
        'src.core.performance_optimizer',
        'src.core.platform_fs',
        'src.core.plugin_autoload',
        'src.core.plugin_manifest',
        'src.core.plugin_market',
        'src.core.pre_action_check',
        'src.core.predictive_precompute',
        'src.core.predictor',
        'src.core.principle_extractor',
        'src.core.profile_manager',
        'src.core.progressive_context',
        'src.core.project_indexer',
        'src.core.prompt_shield',
        'src.core.realtime_push',
        'src.core.regression_shield',
        'src.core.sandbox',
        'src.core.sdb_framework',
        'src.core.secret_scanner',
        'src.core.security',
        'src.core.self_modify',
        'src.core.self_updater',
        'src.core.session_archiver',
        'src.core.session_identity',
        'src.core.smart_router',
        'src.core.super_brain',
        'src.core.task_progress',
        'src.core.telegram_router',
        'src.core.unified_loop',
        'src.core.usage_insights',
        'src.core.version_guard',
        'src.core.versioned_memory',
        'src.core.voice_io',
        'src.core.watchdog',
        'src.core.webhook',
        'src.core.websocket_plugin',
        'src.core.win_admin',
        'src.core.workflow_engine',
        'src.core.workspace_manager',
        # Common deps
# Common deps
        'yaml', 'openai', 'httpx', 'fastapi', 'uvicorn',
        'pydantic', 'jinja2', 'Crypto', 'Crypto.Cipher',
        'Crypto.Cipher.AES', 'aiohttp', 'starlette',
        'anyio', 'sniffio', 'h11', 'websockets', 'psutil',
        'numpy', 'aiofiles', 'packaging',
    ],
    hookspath=[],
    excludes=['tkinter','matplotlib','pandas','scipy','jupyter','IPython','PyQt5','PyQt6','PySide2','PySide6','wx'],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],
    name='meshctx-desktop', debug=False, strip=False, upx=True,
    console=True, icon='logo.ico',
    version=os.path.join(_here, 'version_info.txt'))

if sys.platform == 'darwin':
    app = BUNDLE(exe, name='meshctx-desktop.app', icon='logo.icns',
        bundle_identifier='com.meshctx.desktop',
        info_plist={
            'NSHighResolutionCapable': 'True',
            'CFBundleShortVersionString': '2.77.0',
            'CFBundleVersion': '2.77.0',
        }, version=os.path.join(_here, 'version_info.txt'))
