"""AGENTS.md Protocol — v2.88
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Claude Code #1 Feature Request: AGENTS.md 👍5177

meshctx直接支持AGENTS.md协议:
- 读取项目AGENTS.md配置
- 自动生成AGENTS.md模板
- 多项目聚合规则
- 与context_restorer(v2.70)联动
"""
import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class AgentsConfig:
    """AGENTS.md配置"""
    project_name: str = ""
    description: str = ""
    build_command: str = ""
    test_command: str = ""
    language: str = ""
    framework: str = ""
    code_style: str = ""
    security_rules: List[str] = field(default_factory=list)
    ignore_patterns: List[str] = field(default_factory=list)
    custom_rules: Dict[str, str] = field(default_factory=dict)


class AgentsMDProtocol:
    """AGENTS.md协议支持"""

    _DEFAULT_TEMPLATE = """# AGENTS.md — {project_name}

## Project Overview
{description}

## Build & Test
- Build: `{build_command}`
- Test: `{test_command}`

## Tech Stack
- Language: {language}
- Framework: {framework}

## Code Style
{code_style}

## Security Rules
{security_rules}

## Ignore Patterns
{ignore_patterns}

## Custom Rules
{custom_rules}

---

> Generated by meshctx v2.88 — AGENTS.md protocol
> First requested by Claude Code community: 👍5177
"""

    def __init__(self, workspace: Optional[Path] = None):
        self.workspace = workspace or Path.cwd()
        self._configs: Dict[str, AgentsConfig] = {}

    # ── Parse ──────────────────────────────────────────

    def parse(self, filepath: Optional[Path] = None) -> AgentsConfig:
        """解析AGENTS.md文件"""
        path = filepath or self.workspace / "AGENTS.md"
        if not path.exists():
            # Try CLAUDE.md as fallback
            path = self.workspace / "CLAUDE.md"
        if not path.exists():
            return AgentsConfig()

        content = path.read_text(encoding="utf-8", errors="replace")
        config = AgentsConfig()

        # 解析YAML-like配置块
        in_code_block = False
        current_section = ""

        for line in content.split("\n"):
            line = line.strip()

            # 跳过程序代码块
            if line.startswith("```"):
                in_code_block = not in_code_block
                continue
            if in_code_block:
                continue

            # 节标题
            if line.startswith("## "):
                current_section = line[3:].strip().lower()
                continue

            # 键值对 (支持 `Key: Value` 和 `- Key: Value`)
            clean_line = line.lstrip("- ").strip()
            if ":" in clean_line and not clean_line.startswith("#"):
                key, _, value = clean_line.partition(":")
                key = key.strip().lower()
                value = value.strip().strip("`")

                if "project" in current_section or "overview" in current_section:
                    if key == "name" or key == "project":
                        config.project_name = value
                    elif key == "description":
                        config.description = value
                elif "build" in current_section or "test" in current_section:
                    if "build" in key:
                        config.build_command = value.strip("`")
                    elif "test" in key:
                        config.test_command = value.strip("`")
                elif "tech" in current_section or "stack" in current_section:
                    if key == "language":
                        config.language = value
                    elif key == "framework":
                        config.framework = value
                elif "style" in current_section or "code" in current_section:
                    config.code_style += line + "\n"
                elif "security" in current_section:
                    config.security_rules.append(line)
                elif "ignore" in current_section:
                    config.ignore_patterns.append(value)

        return config

    # ── Generate ────────────────────────────────────────

    def generate(self, config: Optional[AgentsConfig] = None,
                output_path: Optional[Path] = None) -> str:
        """生成AGENTS.md"""
        if config is None:
            # 自动检测项目配置
            config = self._auto_detect()

        security_rules = "\n".join(
            f"- {r}" for r in (config.security_rules or [
                "All changes must pass CI",
                "Never commit secrets or API keys",
                "Review diff before committing",
                "Run tests before push",
            ])
        )
        ignore_patterns = "\n".join(
            f"- {p}" for p in (config.ignore_patterns or [
                "node_modules/", "__pycache__/", "*.pyc",
                ".env", "dist/", "build/", ".git/",
            ])
        )
        custom_rules = "\n".join(
            f"- **{k}**: {v}" for k, v in (config.custom_rules or {
                "max_file_size": "500 lines per file recommended",
                "docstring_required": "All public functions must have docstrings",
                "type_hints": "Use type hints for all function signatures",
            }).items()
        )

        content = self._DEFAULT_TEMPLATE.format(
            project_name=config.project_name or self.workspace.name,
            description=config.description or "An awesome project",
            build_command=config.build_command or "make build",
            test_command=config.test_command or "pytest",
            language=config.language or "Python",
            framework=config.framework or "FastAPI",
            code_style=config.code_style or "- PEP 8 compliant\n- Max line length: 100\n- Use black for formatting",
            security_rules=security_rules,
            ignore_patterns=ignore_patterns,
            custom_rules=custom_rules,
        )

        if output_path:
            output_path.write_text(content, encoding="utf-8")

        return content

    def _auto_detect(self) -> AgentsConfig:
        """自动检测项目配置"""
        config = AgentsConfig()

        # 检测语言
        py_files = list(self.workspace.glob("*.py")) + list(self.workspace.glob("**/*.py"))
        js_files = list(self.workspace.glob("*.js")) + list(self.workspace.glob("**/*.js"))
        if len(py_files) > len(js_files):
            config.language = "Python"
        elif js_files:
            config.language = "JavaScript/TypeScript"

        # 检测框架
        req = self.workspace / "requirements.txt"
        if req.exists():
            content = req.read_text().lower()
            if "fastapi" in content:
                config.framework = "FastAPI"
            elif "flask" in content:
                config.framework = "Flask"
            elif "django" in content:
                config.framework = "Django"

        # 检测测试命令
        if (self.workspace / "pyproject.toml").exists():
            config.test_command = "pytest"
        elif (self.workspace / "Makefile").exists():
            config.test_command = "make test"
        elif (self.workspace / "package.json").exists():
            config.test_command = "npm test"

        # 检测构建命令
        if (self.workspace / "Makefile").exists():
            config.build_command = "make"
        elif (self.workspace / "setup.py").exists():
            config.build_command = "python setup.py build"

        config.project_name = self.workspace.name
        return config

    # ── Multi-Project ──────────────────────────────────

    def discover_all(self, root: Optional[Path] = None) -> List[Dict]:
        """发现所有项目的AGENTS.md"""
        root = root or self.workspace
        agents_files = list(root.rglob("AGENTS.md")) + list(root.rglob("CLAUDE.md"))
        results = []
        for f in agents_files:
            try:
                config = self.parse(f)
                results.append({
                    "path": str(f.relative_to(root)),
                    "project": config.project_name or f.parent.name,
                    "language": config.language,
                    "framework": config.framework,
                })
            except Exception:
                pass
        return results

    # ── Import/Export ──────────────────────────────────

    def export_to_context_restorer(self, config: AgentsConfig):
        """导出到context_restorer"""
        try:
            from .context_restorer import get_context_restorer
            cr = get_context_restorer()
            ctx = cr.detect_project(self.workspace)
            ctx.preferences["agents_md"] = {
                "build": config.build_command,
                "test": config.test_command,
                "language": config.language,
                "framework": config.framework,
                "rules": config.custom_rules,
            }
        except ImportError:
            pass

    def export_claude_format(self, config: Optional[AgentsConfig] = None) -> str:
        """导出为Claude Code兼容的CLAUDE.md格式"""
        if config is None:
            config = self._auto_detect()

        lines = [
            f"# CLAUDE.md",
            f"",
            f"## Project: {config.project_name or self.workspace.name}",
            f"",
            f"### Build & Test Commands",
            f"- Build: `{config.build_command or 'make'}`",
            f"- Test: `{config.test_command or 'pytest'}`",
            f"- Lint: `pre-commit run --all-files`",
            f"",
            f"### Code Style",
            f"- Language: {config.language or 'Python'}",
            f"- Framework: {config.framework or 'FastAPI'}",
            f"{config.code_style or '- PEP 8, max line 100, black formatting'}",
            f"",
            f"### Important Rules",
        ]

        for rule in (config.security_rules or [
            "Never push secrets or API keys",
            "Run full test suite before merging",
            "All changes must pass CI",
        ]):
            lines.append(f"- {rule}")

        lines.extend([
            f"",
            f"### Project Structure",
            f"```",
            f"src/       # Source code",
            f"tests/     # Test files",
            f"docs/      # Documentation",
            f"```",
            f"",
            f"> Generated by meshctx v2.89 — AGENTS.md ↔ CLAUDE.md bidirectional",
        ])

        content = "\n".join(lines)

        # 同时写入CLAUDE.md
        claude_path = self.workspace / "CLAUDE.md"
        claude_path.write_text(content, encoding="utf-8")

        return content

    def import_claude_format(self, filepath: Optional[Path] = None) -> AgentsConfig:
        """从Claude Code的CLAUDE.md导入配置"""
        path = filepath or self.workspace / "CLAUDE.md"
        return self.parse(path)

    # ── MCP Tools Loader ───────────────────────────────

    def load_claude_mcp_config(self, mcp_path: Optional[Path] = None) -> List[Dict]:
        """加载Claude Code的MCP配置文件"""
        import json
        mcp_path = mcp_path or Path.home() / ".claude" / "mcp.json"
        if not mcp_path.exists():
            mcp_path = Path.home() / ".config" / "claude" / "mcp_servers.json"
        if not mcp_path.exists():
            return []

        try:
            config = json.loads(mcp_path.read_text())
            servers = config.get("mcpServers", config)
            tools = []
            for name, info in servers.items():
                tools.append({
                    "name": name,
                    "command": info.get("command", ""),
                    "args": info.get("args", []),
                    "env": info.get("env", {}),
                    "source": "Claude Code MCP",
                })
            return tools
        except Exception:
            return []

    def sync_all_formats(self) -> Dict:
        """全格式同步: AGENTS.md ↔ CLAUDE.md"""
        config = self._auto_detect()
        agents_content = self.generate(config)
        claude_content = self.export_claude_format(config)

        # 写入两个文件
        (self.workspace / "AGENTS.md").write_text(agents_content, encoding="utf-8")
        (self.workspace / "CLAUDE.md").write_text(claude_content, encoding="utf-8")

        mcp_tools = self.load_claude_mcp_config()

        return {
            "agents_md_bytes": len(agents_content),
            "claude_md_bytes": len(claude_content),
            "mcp_tools_loaded": len(mcp_tools),
            "mcp_tools": mcp_tools[:5],
            "bidirectional": True,
        }

    # ── Stats ──────────────────────────────────────────

    def get_stats(self) -> Dict:
        agents_files = self.discover_all()
        return {
            "agents_md_files_found": len(agents_files),
            "files": agents_files,
            "template_available": True,
            "claude_code_feature_request": "AGENTS.md 👍5177 — meshctx原生支持",
            "generate_command": "meshctx agents init",
        }

    def vs_claude_code_agents(self) -> str:
        """对比Claude Code的AGENTS.md支持"""
        return """━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AGENTS.md: meshctx vs Claude Code
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Claude Code:   👍5177 社区请求 — 尚未实现
meshctx:      ✅ v2.88 原生支持
  • 自动解析: AGENTS.md + CLAUDE.md
  • 自动生成: meshctx agents init
  • 多项目发现: 递归扫描
  • 自动检测: 语言/框架/测试/构建
  • 联动: context_restorer记忆项目配置
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""


# 单例
_protocol: Optional[AgentsMDProtocol] = None


def get_agents_protocol() -> AgentsMDProtocol:
    global _protocol
    if _protocol is None:
        _protocol = AgentsMDProtocol()
    return _protocol
