"""
meshctx — PPT Generator Tool (对标 扣子 Coze AI写作/PPT)

通过 python-pptx 生成 PowerPoint 演示文稿。
无依赖时可返回 markdown 版提纲（优雅降级）。

Tool name: ppt_generate
"""

import io
import os
import base64
from typing import Any


def _ensure_pptx():
    try:
        from pptx import Presentation  # noqa: F401
        from pptx.util import Inches, Pt, Emu  # noqa: F401
        from pptx.dml.color import RGBColor  # noqa: F401
        from pptx.enum.text import PP_ALIGN  # noqa: F401
        return True
    except ImportError:
        return False


# ── Markdown fallback (no python-pptx) ──

def _generate_markdown_outline(title: str, slides: list[dict]) -> str:
    """Generate a markdown outline when python-pptx is not available."""
    lines = [f"# {title}", "", f"*Auto-generated by meshctx PPT Generator*", ""]
    for i, slide in enumerate(slides, 1):
        # Accept both dict and string slides
        if isinstance(slide, str):
            slide = {"title": slide}
        s_title = slide.get("title", f"Slide {i}")
        content = slide.get("content", "")
        bullet = slide.get("bullet_points", [])
        layout = slide.get("layout", "blank")

        lines.append(f"## Slide {i}: {s_title}")
        lines.append(f"Layout: `{layout}`")
        lines.append("")
        if content:
            lines.append(content)
            lines.append("")
        if bullet:
            for b in bullet:
                lines.append(f"- {b}")
            lines.append("")
        if slide.get("image_hint"):
            lines.append(f"[Image: {slide['image_hint']}]")
            lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ── Full PPTX generation ──

def _build_pptx(title: str, slides: list[dict], theme: str = "default") -> bytes:
    """Build a .pptx file in memory and return bytes."""
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    # Slide dimensions: 16:9 widescreen
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Theme colors
    themes = {
        "default": {"bg": (0xFFFFFF, 0x000000), "accent": (0x2563EB, 0xFFFFFF)},
        "dark": {"bg": (0x1E1E2E, 0xCDD6F4), "accent": (0x89B4FA, 0x1E1E2E)},
        "warm": {"bg": (0xFFFBEB, 0x1C1917), "accent": (0xD97706, 0xFFFFFF)},
        "green": {"bg": (0xF0FDF4, 0x166534), "accent": (0x16A34A, 0xFFFFFF)},
    }
    tc = themes.get(theme, themes["default"])
    bg_color = tc["bg"]
    accent_color = tc["accent"]

    # Title slide
    title_slide_layout = prs.slide_layouts[0]  # Title + Subtitle
    s = prs.slides.add_slide(title_slide_layout)
    s.background.fill.solid()
    s.background.fill.fore_color.rgb = RGBColor(*bg_color)
    if s.shapes.title:
        s.shapes.title.text = title
        s.shapes.title.text_frame.paragraphs[0].font.size = Pt(44)
        s.shapes.title.text_frame.paragraphs[0].font.color.rgb = RGBColor(*accent_color[:2])

    # Content slides
    BULLET_LAYOUT = prs.slide_layouts[1]  # Title + Content
    BLANK_LAYOUT = prs.slide_layouts[6]  # Blank

    for slide_data in slides:
        layout_name = slide_data.get("layout", "content")
        if layout_name in ("title", "title_slide"):
            continue

        layout = BLANK_LAYOUT if layout_name == "blank" else BULLET_LAYOUT
        s = prs.slides.add_slide(layout)
        s.background.fill.solid()
        s.background.fill.fore_color.rgb = RGBColor(*bg_color)

        # Title
        slide_title = slide_data.get("title", "")
        if s.shapes.title and slide_title:
            s.shapes.title.text = slide_title
            s.shapes.title.text_frame.paragraphs[0].font.size = Pt(36)
            s.shapes.title.text_frame.paragraphs[0].font.color.rgb = RGBColor(accent_color[0])

        # Content body
        content = slide_data.get("content", "")
        bullet_points = slide_data.get("bullet_points", [])

        if content or bullet_points:
            left = Inches(1)
            top = Inches(1.8)
            width = Inches(11)
            height = Inches(5)
            txBox = s.shapes.add_textbox(left, top, width, height)
            tf = txBox.text_frame
            tf.word_wrap = True

            if content:
                p = tf.paragraphs[0]
                p.text = content
                p.font.size = Pt(18)
                p.font.color.rgb = RGBColor(bg_color[1])

            for bp in bullet_points:
                p = tf.add_paragraph()
                p.text = f"• {bp}"
                p.font.size = Pt(16)
                p.font.color.rgb = RGBColor(bg_color[1])
                p.space_after = Pt(8)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ── Public Tool API ──

def ppt_generate(title: str, slides: list[dict],
                 theme: str = "default",
                 save_path: str | None = None,
                 format: str = "pptx") -> dict:
    """Generate a PowerPoint presentation.

    Args:
        title: Presentation title.
        slides: List of slide dicts:
            {"title": "Slide Title", "content": "Body text",
             "bullet_points": ["point 1", "point 2"],
             "layout": "content"|"blank", "image_hint": "description"}
        theme: 'default', 'dark', 'warm', 'green'.
        save_path: Path to save .pptx file (auto-generated if None).
        format: 'pptx' (binary file) or 'markdown' (outline text).

    Returns:
        {"ok": True, "save_path": "...", "base64": "...", "slide_count": N,
         "format": ..., "fallback": bool}
    """
    if format == 'markdown' or not _ensure_pptx():
        md = _generate_markdown_outline(title, slides)
        if save_path:
            save_path = os.path.expanduser(save_path)
            os.makedirs(os.path.dirname(save_path) or '.', exist_ok=True)
            with open(save_path, 'w', encoding='utf-8') as f:
                f.write(md)
        return {
            "ok": True,
            "format": "markdown",
            "fallback": not _ensure_pptx(),
            "slide_count": len(slides) + 1,  # +1 for title slide
            "markdown": md,
            "save_path": save_path,
            "hint": "Install python-pptx for real .pptx generation: pip install python-pptx"
            if not _ensure_pptx() else None,
        }

    # Full PPTX generation
    pptx_bytes = _build_pptx(title, slides, theme)
    b64 = base64.b64encode(pptx_bytes).decode()

    if save_path is None:
        import tempfile
        fd, save_path = tempfile.mkstemp(suffix='.pptx', prefix='meshctx_ppt_')
        os.close(fd)

    save_path = os.path.expanduser(save_path)
    os.makedirs(os.path.dirname(save_path) or '.', exist_ok=True)
    with open(save_path, 'wb') as f:
        f.write(pptx_bytes)

    return {
        "ok": True,
        "format": "pptx",
        "fallback": False,
        "slide_count": len(slides) + 1,
        "save_path": save_path,
        "base64": b64,
        "size_bytes": len(pptx_bytes),
    }
